name: CDK Deploy

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1
  STACK_NAME: SecureBucketDevStack

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: evinova-coding-challenge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test || echo "Tests not set up yet"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::768688893088:role/SecureBucketDevStack-MySecureBucketGitHubOIDCRoleEC-zCS5KWlVJtSj
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK Diff
        run: npx cdk diff $STACK_NAME

      - name: CDK Deploy
        run: npx cdk deploy $STACK_NAME --require-approval never
